name: Lint

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install, build, and test
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.CI_BOT_PAT }}" >> .npmrc
          npm ci
          npm run build --if-present
          npm run lint
        env:
          CI: true
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SERVERLESS_ROBOT_ACCESS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SERVERLESS_ROBOT_SECRET_KEY }}


