name: Main Flow

on:
  workflow_dispatch:
    inputs:
      bundleName:
        type: choice
        description: 'The name of the deployment bundle to deploy'
        required: true
        options:
          - 'demo'
          - 'product-qa'
      command:
        type: choice
        description: 'Deployment action'
        required: true
        options:
          - 'deploy'
          - 'destroy'
      stackPassphrase:
        description: 'Stack passphrase'
        required: true
      connectAuthVersion:
        description: 'Connect Authentication version to deploy (if applicable)'
        required: false
      connectWorkflowVersion:
        description: 'Connect Workflow version to deploy (if applicable)'
        required: false
      connectConfigServiceVersion:
        description: 'Connect Configuration Service version to deploy (if applicable)'
        required: false
      cloudFlowVersion:
        description: 'CloudFlow version to deploy (if applicable)'
        required: false
      adminTasksVersion:
        description: 'Admin tasks version to use (if applicable)'
        required: false

jobs:
  preview:
    uses: lserraga/complex-workflows/.github/workflows/deploy.yml@main
    with:
      bundleName: ${{ github.event.inputs.sharedInfrastructureVersion }}
      command: 'preview'
      connectAuthVersion: ${{ github.event.inputs.connectAuthVersion }}
      connectWorkflowVersion: ${{ github.event.inputs.connectWorkflowVersion }}
      connectConfigServiceVersion: ${{ github.event.inputs.connectConfigServiceVersion }}
      cloudFlowVersion: ${{ github.event.inputs.cloudFlowVersion }}
      adminTasksVersion: ${{ github.event.inputs.adminTasksVersion }}
    secrets:
      stackPassphrase: ${{ github.event.inputs.stackPassphrase }}
